### ISSUE TITLE
Can't commit.

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#10] opened 2018-07-30 16:47 UTC
The commit window open correctly but commit button dont work, here is stack trace error.
```
2018-07-30 11:45:35,283 [ 140907]  ERROR - llij.ide.plugins.PluginManager - No such child: 0 
java.lang.ArrayIndexOutOfBoundsException: No such child: 0
	at java.awt.Container.getComponent(Container.java:334)
	at com.github.syuchan1005.gitprefix.commit.PrefixCheckinHandler.lambda$beforeCheckin$0(PrefixCheckinHandler.java:54)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.syuchan1005.gitprefix.commit.PrefixCheckinHandler.beforeCheckin(PrefixCheckinHandler.java:53)
	at com.intellij.openapi.vcs.checkin.CheckinHandler.beforeCheckin(CheckinHandler.java:81)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.d(CommitChangeListDialog.java:829)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:809)
	at com.intellij.openapi.vcs.checkin.ReformatBeforeCheckinHandler.a(ReformatBeforeCheckinHandler.java:49)
	at com.intellij.openapi.vcs.checkin.ReformatBeforeCheckinHandler.runCheckinHandlers(ReformatBeforeCheckinHandler.java:58)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:855)
	at com.intellij.openapi.vcs.checkin.RearrangeBeforeCheckinHandler.a(RearrangeBeforeCheckinHandler.java:44)
	at com.intellij.openapi.vcs.checkin.RearrangeBeforeCheckinHandler.runCheckinHandlers(RearrangeBeforeCheckinHandler.java:52)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:855)
	at com.intellij.openapi.vcs.checkin.OptimizeImportsBeforeCheckinHandler.runCheckinHandlers(OptimizeImportsBeforeCheckinHandler.java:58)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:855)
	at com.intellij.openapi.vcs.checkin.CodeCleanupCheckinHandlerFactory$CleanupCodeCheckinHandler.runCheckinHandlers(CodeCleanupCheckinHandlerFactory.java:50)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:855)
	at com.intellij.openapi.vcs.impl.PartialChangesUtil.a(PartialChangesUtil.java:116)
	at com.intellij.openapi.vcs.impl.PartialChangesUtil.computeUnderChangeList(PartialChangesUtil.java:128)
	at com.intellij.openapi.vcs.impl.PartialChangesUtil.runUnderChangeList(PartialChangesUtil.java:115)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.f(CommitChangeListDialog.java:818)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.h(CommitChangeListDialog.java:610)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.a(CommitChangeListDialog.java:1130)
	at com.intellij.openapi.vcs.changes.Waiter.onSuccess(Waiter.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:318)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:303)
	at com.intellij.openapi.vcs.changes.CallbackData.b(CallbackData.java:85)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:196)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:410)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:398)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.b(CommitChangeListDialog.java:1127)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.g(CommitChangeListDialog.java:607)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.access$400(CommitChangeListDialog.java:80)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog$CommitAction.actionPerformed(CommitChangeListDialog.java:557)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:698)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:430)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1690)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1639)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:233)
	at com.intellij.openapi.vcs.changes.ui.CommitChangeListDialog.commitChanges(CommitChangeListDialog.java:154)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.performCheckIn(AbstractCommonCheckinAction.java:87)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.a(AbstractCommonCheckinAction.java:65)
	at com.intellij.openapi.vcs.changes.Waiter.onSuccess(Waiter.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.b(CoreProgressManager.java:318)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:303)
	at com.intellij.openapi.vcs.changes.CallbackData.b(CallbackData.java:85)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue.invokeAfterUpdate(UpdateRequestsQueue.java:196)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:410)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.invokeAfterUpdate(ChangeListManagerImpl.java:398)
	at com.intellij.openapi.vcs.actions.AbstractCommonCheckinAction.actionPerformed(AbstractCommonCheckinAction.java:65)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.actionPerformed(AbstractVcsAction.java:48)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2018.2  Build #PY-182.3684.100 
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2018-07-30 11:45:35,284 [ 140908]  ERROR - llij.ide.plugins.PluginManager - Last Action: CheckinProject 
```

**Comment by u0xaa55** [comment] 2018-07-30 19:46
Same problem here for the v1.5.3.1 on mac/WebStorm. 

Plus couple of other problems:
- I have radio buttons instead of emojis' representation into the commit message left block (may be by design?)
<img width="632" alt="capture d ecran 2018-07-30 a 21 26 25" src="https://user-images.githubusercontent.com/15631355/43418936-cb002e52-943f-11e8-972d-698056a4eb52.png">

- with this scenario: closing project, reopening it, I cannot type more than 2 chars (I tried to add ":sparkles:" but I just could type ":s" and no more char appeared after that) but I can remove chars. Then closing .gitprefix file and reopening it allows me to edit the file. No raised exception.
- I don't have emojis' representation next to the line number in .gitprefix

**Comment by syuchan1005** [comment] 2018-07-31 08:09
Fixed an issue that can not be committed.
icon's invisible problem and input, completation problem separate issue.

**Comment by gollum23** [comment] 2018-07-31 10:36
Thanks, the last version work very well, I could see the icons again in both .gitprefix file and commit window

![screenshot_20180731_053517](https://user-images.githubusercontent.com/1058783/43454714-8645d818-9483-11e8-89e0-42d8e8ac9471.png)

![screenshot_20180731_053610](https://user-images.githubusercontent.com/1058783/43454765-a240ece2-9483-11e8-9525-3e09e1aef7e4.png)

**Comment by u0xaa55** [comment] 2018-07-31 11:07
good job, v1.5.3.2 works for me too. I can see emojis in .gitprefix and commit window. But there is 2 remaining bugs and a new one. I'm opening a new issue for that.

<img width="227" alt="capture d ecran 2018-07-31 a 22 51 22" src="https://user-images.githubusercontent.com/15631355/43486493-4f6d2c10-9514-11e8-87f3-13e2d1ee748a.png">
<img width="337" alt="capture d ecran 2018-07-31 a 22 46 46" src="https://user-images.githubusercontent.com/15631355/43486500-526df9b2-9514-11e8-83d5-74dbca4ea537.png">

Thanks!

**Comment by syuchan1005** [comment] 2018-07-31 22:22
I'm glad I solved a problem that I can not commit.
I will also check for new issues.

**Closed as completed by syuchan1005** 2018-07-31 22:22 UTC
